---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps.togettoyou.com
  resources:
  - sidecargoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.togettoyou.com
  resources:
  - sidecargoes/finalizers
  verbs:
  - update
- apiGroups:
  - apps.togettoyou.com
  resources:
  - sidecargoes/status
  verbs:
  - get
  - patch
  - update
