# permissions for end users to view sidecargoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sidecargo-viewer-role
rules:
- apiGroups:
  - apps.togettoyou.com
  resources:
  - sidecargoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.togettoyou.com
  resources:
  - sidecargoes/status
  verbs:
  - get
