# permissions for end users to edit sidecargoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sidecargo-editor-role
rules:
- apiGroups:
  - apps.togettoyou.com
  resources:
  - sidecargoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.togettoyou.com
  resources:
  - sidecargoes/status
  verbs:
  - get
